#!/usr/bin/expect -f

set timeout 6000
spawn bash /home/developersetup/setup.sh
expect "Installing common developement tools"{
        puts "Developer Setup Started"
        expect "\[Y/n]" {
                send "y\r"
                expect "INSTALLED: [ python ]"{
                        puts "INSTALLED PYTHON PASS"
                }
    }
}




#expect "Deployment successfully completed..." {send "\r"}
interact
